### ISSUE TITLE
using in a multi action switch

### ISSUE THREAD

**Issue by kgNatx** [fredemmott/StreamDeck-AudioMute#11]
Great plugin Fred! Is ther any way to incorporate this into a multi action switch? I want to trigger the visibility of an OBS source at the same time as mute the source..

**Comment by fredemmott** [comment]
Literally allowing it in a multi-action is easy; I think that'll be confusing though, as the multiaction will *toggle* it

It'd probably be good to add explicit "mute" and "unmute" actions (instead of just "toggle"), and permit those in multi actions

**Comment by kgNatx** [comment]
Makes a lot of sense.. would love to see that feature! 

Is it a stream deck thing that duplicate buttons don't update? I like to keep your mute button on the bottom left corner of every stream deck folder and profile 'page' If I mute on one... Then when I switch folders or profiles.. I have to hit it twice cause it doesn't 'know it was already pressed'.

**Comment by fredemmott** [comment]
Could you file a separate issue for that? That's definitely a bug in the plugin - each one should be updating when it becomes visible

**Comment by kgNatx** [comment]
Ok. I'll have to go back and test it again to make sure I'm not confusing that in my memory with a multi action switch.

**Comment by fredemmott** [comment]
Does this work for you?

It adds separate mute/unmute, with multi-action support.

If so I'll include it in the next real update

[com.fredemmott.micmutetoggle.streamDeckPlugin.zip](https://github.com/fredemmott/StreamDeck-AudioMute/files/4842511/com.fredemmott.micmutetoggle.streamDeckPlugin.zip)

**Comment by tmaaz** [comment]
Love your plugin! I was coming here to ask about the possibility of multi-action functionality when I found this thread -- awesome! I downloaded the interim update you posted above, and wanted to let you know a couple things:

1) In this multi-action build, there's no way to turn off the audible feedback 'beep' when the button is pressed. The "Feedback Sounds" checkbox is still there for each of the mute and unmute actions, but it's state -- checked or unchecked -- doesn't seem to make a difference; it always beeps when the button is pressed, regardless of state. (Not only does it always beep, but if a user has kept a single-action version of the currently-available Audio Mute button on their Stream Deck, it suddenly affects _that_ original button as well, overriding the checked/unchecked state of all Audio Mute feedback buttons, and starts automatically playing the feedback sound whenever that button is pressed as well. The only way to make it stop was to uninstall and delete all versions of Audio Mute, then reinstall only the current single-button version, and even then, I had to check/uncheck the Feedback Sounds button to make it finally quit beeping on press).

2) I was recording a test of the mute feature with this new button, to make sure my setup was right before using it on a live stream, and realized that the Feedback beep actually passes through to the live audio / recording... viewers/listeners would be able to audibly hear when I've muted/unmuted my mic. Not necessarily a show-stopper for some folks, but it would be great for users to have the option for it to not beep, and/or only beep in the monitor when it _is_ chosen -- maybe passing the beep sound through only the mic/aux line immediately after the mute is triggered, and immediately before the unmute is triggered?

3) If it's possible to have the beep audio only pass through the monitor or mic/aux line it's affecting, instead of live audio, it would be wonderful if there was a 2nd feedback option that would play a very subtle tone, or chime, every 2 or 3 seconds, to remind the person that the mic they're using is muted. My #1 problem when streaming is remembering that I've muted my mic... the sheer number of times I've come back from a break and accidentally left my mic muted is embarrassingly high. The very reason I was looking for this multi-action version was so that I could add another action to the button, that will play a looped "microphone is muted" sound only while muted, and only in my monitor, so that I would immediately know to turn the mute back off.

**Comment by fredemmott** [comment]
Thanks; I'll investigate 1 as part of this :)

2 is decided by your windows sound settings, and your streaming software settings: it will usually use your default windows audio device to play the sounds, however after it makes a sound, you should be able to change which device it plays through using windows sound settings.

If OBS/XSplit/... is capturing that device, it will be in your stream. Devices like the GoXLR, Elgato Wave, or Roland Octa-Capture give more flexibility either by telling windows they're multiple devices, or by interfacing directly with the streaming software, replacing the standard desktop audio capture.

For a software solution, you probably want voicemeeter banana or virtual audio cable.

Could you file a separate issue for 3 please? I'd also appreciate ideas on how that would work/be configured for buttons other than 'toggle': should the mute button control the persistent sound, or the unmute, or some combination somehow?

**Comment by yashendra2797** [comment]
Any update on this?

**Comment by fredemmott** [comment]
It's not polished enough to release yet (e.g. no default artwork), but it does work; it can be downloaded from the latest green mark on https://github.com/fredemmott/StreamDeck-AudioMute/actions
