### ISSUE TITLE
Plugin stops working when pc is restarted

### ISSUE THREAD

**Issue by JamesRailston** [fredemmott/StreamDeck-AudioMute#20]
Whenever the pc is turned off and then on, the plugin stops working. It doesn't display the device selection dropdown menu or any other information besides the title box to add text to the button. 
I've noticed that when installing the plugin through the stream deck software, the plugin name changes from 'Mic mute' to 'Audio Mute'. I don't know if this is the issue or if there is a different reason.

**Comment by Pilchie** [comment]
I've also noticed that this seems to have stopped working entirely in the last week or so, though I haven't figured out why.

**Comment by JamesRailston** [comment]
You can get the plugin to work again after uninstalling and reinstalling it. However, when my pc is turned off and back on, the plugin stops working.
My thought as to way it stops working is the name change the plugin has once it's installed. Maybe the path the software takes to find the plugin has issues identifying it? Works fine in the instance, but when it restarts and looks for the plugin, it can't find it.

**Comment by fredemmott** [comment]
This isn’t a universal problem, and likely would be if the name were an issue.

- when it stops working, is there still an exe on the plugin directory? (I’m thinking antivirus)
- Are your sound cards external? E.g USB/Bluetooth. Perhaps the plugin is starting before they’re fully connected, though that *should* be handled

**Comment by JamesRailston** [comment]
I'm not entirely sure on where to find the exe, however this is what I can see in the roaming files on the plugins.
![screenshot](https://user-images.githubusercontent.com/77906796/106982711-8327ae00-675c-11eb-8cbf-df8e468a0a4a.jpg)
I can't find the plugin through the 'normal' files via C:\program files\  etc. Only shows the built in plugins.

For antivirus, there are no notifications about any removal, but I am just using the base Windows antivirus, no third-party antivirus. If it was something to do with antivirus, wouldn't it stop the plugin working full stop? 

I am using a different sound card rather than the built-in one on the motherboard, but it's an internal sound card. This is the specific one I'm using.
https://www.amazon.co.uk/gp/product/B00EO6X4XG/ref=ppx_yo_dt_b_asin_image_o03_s00?ie=UTF8&psc=1

After turning on, the plugin is still visible on the stream deck app. However the 'device' and 'feedback' options are gone, along with the 'standard vs specific devices' info. When pressing the button on the deck, it pops up a yellow warning sign to notify an issue. 
The stream deck app still thinks there is a plugin there as you can still uninstall the plugin. 

I hope you can understand what I'm trying to say (dyslexia makes it hard to get a point across sometimes). 
I know the basics to get around a pc, but coding and software development goes over my head. 
I'll look into the antivirus side of things, see if it's an issue with that. Or maybe an issue with the soundcard not booting up properly with the pc. Just confuses me that the plugin loses all function but stream deck doesn't think there's an issue. Also just wanted to bring this to your attention in case others were having a similar issue. :) 

Thanks.

**Comment by fredemmott** [comment]
Thanks - the information you provided rules out both of my ideas, but doesn't lead to any new ones unfortunately :(

When it's not working, can you check if 'sdmicmute' shows up in task manager? An empty property page means that the streamdeck software can't communicate with the plugin - but there's many possible causes for this.

**Comment by JamesRailston** [comment]
I tried disabling StreamDeck in the start up list to see if manually opening the app after a restart affected it. When I opened the app, the sdmicmute.exe did pop up in the task manager details. I pressed the button on the deck, it didn't work. When I looked over at the details window, the exe had disappeared. 

I did a shut down and reboot on the pc with out uninstalling and reinstalling. Kept an eye on the details window when I opened the StreamDeck app, the exe pops up to say it's running, then promptly ends. So it is trying to start, but something is stopping it.

**Comment by fredemmott** [comment]
Could you try:
1. installing https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
2. uninstalling the plugin
3. installing the debug version from https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
4. starting debugview (filter for 'sdmicmute')
5. share the last few messages if any when it exits

**Comment by fredemmott** [comment]
Also, does restarting the streamdeck software without rebooting your PC also break the plugin for you?

**Comment by fredemmott** [comment]
This *might* have been fixed by https://github.com/fredemmott/StreamDeck-AudioMute/releases/tag/v3.0.0rc3

Windows generally remembers and reports devices that are no longer present, MacOS doesn't - which means that the plugin now stores/remembers more information about the device that's configured. This is only meant to be useful on MacOS, but could potentially also solve the problem if Windows is (temporarily?) not reporting a device that was previously present

**Comment by fredemmott** [comment]
> . It doesn't display the device selection dropdown menu or any other information besides the title box to add text to the button.

This sounds like it could be the same as https://github.com/fredemmott/StreamDeck-AudioSwitcher/discussions/27 (different plugin, but the relevant code is shared); if so, it should be fixed by uninstalling the current version of the plugin via 'More Actions...' in the bottom right of the streamdeck software, and installing the version from https://github.com/fredemmott/StreamDeck-AudioMute/releases/tag/v3.0.0rc4

If it's not fixed by that, I'll need some more information from you:
1. download the 'RelWithDebInfo' demos zip for your platform from https://github.com/fredemmott/AudioDeviceLib/releases/tag/v1.0
2. Run the `list-devices.exe` from that zip file in a terminal/command prompt and save the output
3. reboot
4. run `list-devices.exe` again
5. share the output of both runs of list-devices, ideally at https://gist.github.com ; please be clear about which is pre-reboot and which is after

**Comment by fredemmott** [comment]
Plesae reopen/comment if you're still seeing this. Many potential fixes since last reported.
