### ISSUE TITLE
[windows 10] Impossible to unmute input device without streamdeck

### ISSUE THREAD

**Issue by jfessard** [fredemmott/StreamDeck-AudioMute#41]
Windows 10, stream deck 5.0.1.14252
Plugin version 3.0.1

I had muted my logitech webcam through the "toggle mute" button.
![image](https://user-images.githubusercontent.com/11471500/135214821-70aa95c2-ffad-48c7-88f0-ec6cb3c2bbbe.png)

I forgot I did that and was confused why my microphone didn't work. The problem is that even after exiting streamdeck software, it was still muted, and there was NO place in windows that showed that the device was muted, and it was impossible to unmute it. (see picture)

Once I unmuted by pushing the streamdeck button, the mic was back to working.
If my streamdeck fails while the input is muted, it could be difficult to get it working without access to the plugin/command.

Is there any place in windows 10 that shows the input device is muted when using Toggle mute? I was not able to find it (the sound devices showed it unmuted and at full volume, they just didn't produce anything)

![image](https://user-images.githubusercontent.com/11471500/135214788-401fe874-b1de-444f-85f4-edafbadb7f78.png)

**Comment by Zetri** [comment]
Yes, for some reason it's complicated to mute/unmute the mic on Windows 10, here are the steps.

- Instead of clicking on "Device properties", continue farther down and click on "Sound Control Panel"  under "Related Settings".

![image](https://user-images.githubusercontent.com/39783742/135277047-637dcb37-b949-4923-a124-617c2baed5df.png)

- Double click on your microphone, found under the "Recording" tad, to open it's property.

![image](https://user-images.githubusercontent.com/39783742/135277571-c77374c0-b09e-4165-b482-b93487c876a3.png)

- Click on the "Levels" tab and you will find the volume and the mute/unmute button.

![image](https://user-images.githubusercontent.com/39783742/135277998-b6ef1101-f221-47c1-a4f6-573c97efd209.png)

**Comment by jfessard** [comment]
Oh yes there it is. Silly Microsoft, leaving that mute only in the old Control panel sound options, and not the windows 10 "native" sound settings...
I couldn't get to that menu from the steps you outlined (probably different windows versions, mine is 21H1 / 19043.1237 but the control panel -> sound through the start menu did the trick. 
Thanks for the tip and the screenshots!
