### ISSUE TITLE
Windows Sleep/Hibernation

### ISSUE THREAD

**Issue by fabiopedrosa** [fredemmott/StreamDeck-AudioMute#9]
I believe the plugin is preventing windows from sleeping/hibernating. You can check `powercfg /requests` to see its showing as an active audio stream, and thus won't sleep. Can you try to reproduce this?

**Comment by fredemmott** [comment]
I'll take a look; there's no active audio stream, however it does set up a callback so that windows tells it when the state is changed by something else, which could be considered the same thing.

Also, I'm sorry it took so long to respond; at some point last year, the GitHub notifications settings for several of my personal projects were changed - none of my actual work projects were affected, so I did not notice until mentioned on a new issue.

**Comment by fredemmott** [comment]
Can repro after touching the button; does not repro until button is pressed.

**Comment by fredemmott** [comment]
This isn't the handle; the feedback sound playback keeps it  open. I assumed that PlaySound would clean up after itself, but looks like I need to do something else after.

**Comment by fredemmott** [comment]
Tried moving it to another thread, which led to figuring out htat non-async PlaySound 'never' returns: I accidentally have multi-minute long wav files here.

**Comment by fredemmott** [comment]
Yeah, this is just an issue with the wav files; it's not delaying it forever - roughly 3.5 minutes
